`steps-00-init`: Fail early, describe the phases

diff --git a/steps-00-init b/steps-00-init
--- a/steps-00-init
+++ b/steps-00-init
@@ -8,8 +8,13 @@
 # Eg. import the initial SSH key so the host can authenticate
 # us and be managed via SSH in a non-interactive way further.
 
+# 0, Fail early:
+set -e
+
+# 1, Import the current/configured SSH key:
 ssh-copy-id -o StrictHostKeyChecking=accept-new $1
 
+# 2, Test the SSH key:
 echo "Testing key-based SSH-auth:"
 echo
 ssh $1 'echo -e "$(date)  $(id) logged in succesfully on $(hostname)"' 2>/dev/null
